name: unet
key: 42
parameters: 
  img_h: 32
  img_w: 32
  batch_size: 3
  channels: [[1,64],[64,64]]
  N_channels: 2
  kernel_sizes: [[3,3],[3,3]]
  kernel_stride: [[1,1],[1,1]]
  momentum: 0.99
  eps: 0.00001





